# Generated by Django 5.0.4 on 2024-04-23 23:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('contatos', models.CharField(blank=True, max_length=25, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('descrição', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reclamante', models.CharField(max_length=200)),
                ('condominio', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=200)),
                ('unidade', models.CharField(max_length=20)),
                ('reclamado', models.CharField(max_length=200)),
                ('ocorrencia', models.TextField(max_length=3000)),
            ],
            options={
                'ordering': ['condominio'],
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcoes', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['opcoes'],
            },
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('condominio', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=200)),
                ('unidade', models.CharField(max_length=20)),
                ('incoveniente', models.TextField(max_length=500)),
                ('sugestao_de_melhoria', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['condominio'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoPrestadorServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classificacao', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.empresas')),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nome_segmento', to='gestao.segmento'),
        ),
    ]
